# Auto-generated by sqlacodegen. Do not edit manually.
# Regenerate with: cd db && scripts\generate_models.bat

from typing import Optional
import datetime
import decimal
import uuid

from sqlalchemy import CheckConstraint, DateTime, Double, ForeignKeyConstraint, Index, Integer, Numeric, PrimaryKeyConstraint, String, Text, Uuid, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

class Base(DeclarativeBase):
    pass


class ModelRuns(Base):
    __tablename__ = 'model_runs'
    __table_args__ = (
        PrimaryKeyConstraint('model_run_id', name='model_runs_pkey'),
    )

    model_run_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    model_name: Mapped[str] = mapped_column(Text, nullable=False)

    model_reports: Mapped[list['ModelReports']] = relationship('ModelReports', back_populates='model_run')


class Publishers(Base):
    __tablename__ = 'publishers'
    __table_args__ = (
        PrimaryKeyConstraint('publisher_id', name='publishers_pkey'),
    )

    publisher_name: Mapped[str] = mapped_column(Text, nullable=False)
    publisher_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)

    campaigns: Mapped[list['Campaigns']] = relationship('Campaigns', back_populates='publisher')
    model_logs: Mapped[list['ModelLogs']] = relationship('ModelLogs', back_populates='publisher')
    anomaly_periods: Mapped[list['AnomalyPeriods']] = relationship('AnomalyPeriods', back_populates='publisher')
    derived_metrics: Mapped[list['DerivedMetrics']] = relationship('DerivedMetrics', back_populates='publisher')
    model_reports: Mapped[list['ModelReports']] = relationship('ModelReports', back_populates='publisher')
    raw_metrics: Mapped[list['RawMetrics']] = relationship('RawMetrics', back_populates='publisher')


class SchemaMigrations(Base):
    __tablename__ = 'schema_migrations'
    __table_args__ = (
        PrimaryKeyConstraint('version', name='schema_migrations_pkey'),
    )

    version: Mapped[str] = mapped_column(String, primary_key=True)


class Campaigns(Base):
    __tablename__ = 'campaigns'
    __table_args__ = (
        ForeignKeyConstraint(['publisher_id'], ['publishers.publisher_id'], ondelete='CASCADE', name='campaigns_publisher_id_fkey'),
        PrimaryKeyConstraint('campaign_id', name='campaigns_pkey')
    )

    campaign_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    publisher_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False)
    start_date: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False)
    end_date: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True))

    publisher: Mapped['Publishers'] = relationship('Publishers', back_populates='campaigns')
    anomaly_periods: Mapped[list['AnomalyPeriods']] = relationship('AnomalyPeriods', back_populates='campaign')
    derived_metrics: Mapped[list['DerivedMetrics']] = relationship('DerivedMetrics', back_populates='campaign')
    model_reports: Mapped[list['ModelReports']] = relationship('ModelReports', back_populates='campaign')
    raw_metrics: Mapped[list['RawMetrics']] = relationship('RawMetrics', back_populates='campaign')


class ModelLogs(Base):
    __tablename__ = 'model_logs'
    __table_args__ = (
        CheckConstraint('score >= 0::numeric AND score <= 1::numeric', name='model_logs_score_check'),
        ForeignKeyConstraint(['publisher_id'], ['publishers.publisher_id'], ondelete='CASCADE', name='model_logs_publisher_id_fkey'),
        PrimaryKeyConstraint('publisher_id', 'log_timestamp', name='model_logs_pkey'),
        Index('model_logs_log_timestamp_idx', 'log_timestamp')
    )

    log_timestamp: Mapped[datetime.datetime] = mapped_column(DateTime(True), primary_key=True)
    model_name: Mapped[str] = mapped_column(Text, nullable=False)
    fraud_type: Mapped[str] = mapped_column(Text, nullable=False)
    score: Mapped[decimal.Decimal] = mapped_column(Numeric(3, 2), nullable=False)
    publisher_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)

    publisher: Mapped['Publishers'] = relationship('Publishers', back_populates='model_logs')


class AnomalyPeriods(Base):
    __tablename__ = 'anomaly_periods'
    __table_args__ = (
        ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ondelete='CASCADE', name='anomaly_periods_campaign_id_fkey'),
        ForeignKeyConstraint(['publisher_id'], ['publishers.publisher_id'], ondelete='CASCADE', name='anomaly_periods_publisher_id_fkey'),
        PrimaryKeyConstraint('period_id', 'publisher_id', 'campaign_id', 'start_timestamp', name='anomaly_periods_pkey'),
        Index('anomaly_periods_start_timestamp_idx', 'start_timestamp')
    )

    period_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, server_default=text('gen_random_uuid()'))
    publisher_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    campaign_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    anomaly_type: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'anomaly'::text"))
    start_timestamp: Mapped[datetime.datetime] = mapped_column(DateTime(True), primary_key=True)
    log_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text('0'))
    end_timestamp: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True))
    avg_score: Mapped[Optional[float]] = mapped_column(Double(53))
    max_score: Mapped[Optional[float]] = mapped_column(Double(53))

    campaign: Mapped['Campaigns'] = relationship('Campaigns', back_populates='anomaly_periods')
    publisher: Mapped['Publishers'] = relationship('Publishers', back_populates='anomaly_periods')


class DerivedMetrics(Base):
    __tablename__ = 'derived_metrics'
    __table_args__ = (
        ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ondelete='CASCADE', name='derived_metrics_campaign_id_fkey'),
        ForeignKeyConstraint(['publisher_id'], ['publishers.publisher_id'], ondelete='CASCADE', name='derived_metrics_publisher_id_fkey'),
        PrimaryKeyConstraint('publisher_id', 'bucket_timestamp', 'campaign_id', name='derived_metrics_pkey'),
        Index('derived_metrics_bucket_timestamp_idx', 'bucket_timestamp')
    )

    bucket_timestamp: Mapped[datetime.datetime] = mapped_column(DateTime(True), primary_key=True)
    publisher_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    campaign_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    sample_size: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text('250'))
    impressions_mean: Mapped[Optional[float]] = mapped_column(Double(53))
    clicks_mean: Mapped[Optional[float]] = mapped_column(Double(53))
    conversions_mean: Mapped[Optional[float]] = mapped_column(Double(53))
    impressions_std: Mapped[Optional[float]] = mapped_column(Double(53))
    clicks_std: Mapped[Optional[float]] = mapped_column(Double(53))
    conversions_std: Mapped[Optional[float]] = mapped_column(Double(53))
    impressions_weighted_mean: Mapped[Optional[float]] = mapped_column(Double(53))
    clicks_weighted_mean: Mapped[Optional[float]] = mapped_column(Double(53))
    conversions_weighted_mean: Mapped[Optional[float]] = mapped_column(Double(53))

    campaign: Mapped['Campaigns'] = relationship('Campaigns', back_populates='derived_metrics')
    publisher: Mapped['Publishers'] = relationship('Publishers', back_populates='derived_metrics')


class ModelReports(Base):
    __tablename__ = 'model_reports'
    __table_args__ = (
        ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ondelete='CASCADE', name='model_reports_campaign_id_fkey'),
        ForeignKeyConstraint(['model_run_id'], ['model_runs.model_run_id'], ondelete='CASCADE', name='model_reports_model_run_id_fkey'),
        ForeignKeyConstraint(['publisher_id'], ['publishers.publisher_id'], ondelete='CASCADE', name='model_reports_publisher_id_fkey'),
        PrimaryKeyConstraint('model_run_id', 'publisher_id', 'campaign_id', 'report_timestamp', name='model_reports_pkey')
    )

    model_run_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    publisher_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    report_timestamp: Mapped[datetime.datetime] = mapped_column(DateTime(True), primary_key=True)
    campaign_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    report_data: Mapped[Optional[dict]] = mapped_column(JSONB)

    campaign: Mapped['Campaigns'] = relationship('Campaigns', back_populates='model_reports')
    model_run: Mapped['ModelRuns'] = relationship('ModelRuns', back_populates='model_reports')
    publisher: Mapped['Publishers'] = relationship('Publishers', back_populates='model_reports')


class RawMetrics(Base):
    __tablename__ = 'raw_metrics'
    __table_args__ = (
        ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ondelete='CASCADE', name='raw_metrics_campaign_id_fkey'),
        ForeignKeyConstraint(['publisher_id'], ['publishers.publisher_id'], ondelete='CASCADE', name='raw_metrics_publisher_id_fkey'),
        PrimaryKeyConstraint('publisher_id', 'bucket_timestamp', 'campaign_id', name='raw_metrics_pkey'),
        Index('raw_metrics_bucket_timestamp_idx', 'bucket_timestamp')
    )

    bucket_timestamp: Mapped[datetime.datetime] = mapped_column(DateTime(True), primary_key=True)
    impression_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text('0'))
    click_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text('0'))
    conversion_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text('0'))
    publisher_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    campaign_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)

    campaign: Mapped['Campaigns'] = relationship('Campaigns', back_populates='raw_metrics')
    publisher: Mapped['Publishers'] = relationship('Publishers', back_populates='raw_metrics')
