# Auto-generated by sqlacodegen. Do not edit manually.
# Regenerate with: cd db && ./scripts/generate_models.sh

from typing import Optional
import datetime
import decimal
import uuid

from sqlalchemy import CheckConstraint, DateTime, ForeignKeyConstraint, Index, Integer, Numeric, PrimaryKeyConstraint, String, Text, Uuid, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

class Base(DeclarativeBase):
    pass


class ModelRuns(Base):
    __tablename__ = 'model_runs'
    __table_args__ = (
        PrimaryKeyConstraint('model_run_id', name='model_runs_pkey'),
    )

    model_run_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    model_name: Mapped[str] = mapped_column(Text, nullable=False)

    ml_reports: Mapped[list['MlReports']] = relationship('MlReports', back_populates='model_run')


class Publishers(Base):
    __tablename__ = 'publishers'
    __table_args__ = (
        PrimaryKeyConstraint('publisher_id', name='publishers_pkey'),
    )

    publisher_name: Mapped[str] = mapped_column(Text, nullable=False)
    publisher_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)

    campaign: Mapped[list['Campaign']] = relationship('Campaign', back_populates='publisher')
    ml_reports: Mapped[list['MlReports']] = relationship('MlReports', back_populates='publisher')
    model_logs: Mapped[list['ModelLogs']] = relationship('ModelLogs', back_populates='publisher')
    raw_metrics: Mapped[list['RawMetrics']] = relationship('RawMetrics', back_populates='publisher')


class SchemaMigrations(Base):
    __tablename__ = 'schema_migrations'
    __table_args__ = (
        PrimaryKeyConstraint('version', name='schema_migrations_pkey'),
    )

    version: Mapped[str] = mapped_column(String, primary_key=True)


class Campaign(Base):
    __tablename__ = 'campaign'
    __table_args__ = (
        ForeignKeyConstraint(['publisher_id'], ['publishers.publisher_id'], ondelete='CASCADE', name='campaign_publisher_id_fkey'),
        PrimaryKeyConstraint('campaign_id', name='campaign_pkey')
    )

    campaign_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    publisher_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False)
    start_date: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False)
    end_date: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True))

    publisher: Mapped['Publishers'] = relationship('Publishers', back_populates='campaign')
    raw_metrics: Mapped[list['RawMetrics']] = relationship('RawMetrics', back_populates='campaign')


class MlReports(Base):
    __tablename__ = 'ml_reports'
    __table_args__ = (
        ForeignKeyConstraint(['model_run_id'], ['model_runs.model_run_id'], ondelete='CASCADE', name='ml_reports_model_run_id_fkey'),
        ForeignKeyConstraint(['publisher_id'], ['publishers.publisher_id'], ondelete='CASCADE', name='ml_reports_publisher_id_fkey'),
        PrimaryKeyConstraint('model_run_id', 'publisher_id', 'report_timestamp', name='ml_reports_pkey')
    )

    model_run_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    publisher_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    report_timestamp: Mapped[datetime.datetime] = mapped_column(DateTime(True), primary_key=True)
    report_data: Mapped[Optional[dict]] = mapped_column(JSONB)

    model_run: Mapped['ModelRuns'] = relationship('ModelRuns', back_populates='ml_reports')
    publisher: Mapped['Publishers'] = relationship('Publishers', back_populates='ml_reports')


class ModelLogs(Base):
    __tablename__ = 'model_logs'
    __table_args__ = (
        CheckConstraint('score >= 0::numeric AND score <= 1::numeric', name='model_logs_score_check'),
        ForeignKeyConstraint(['publisher_id'], ['publishers.publisher_id'], ondelete='CASCADE', name='model_logs_publisher_id_fkey'),
        PrimaryKeyConstraint('publisher_id', 'timestamp', name='model_logs_pkey'),
        Index('model_logs_timestamp_idx', 'timestamp')
    )

    timestamp: Mapped[datetime.datetime] = mapped_column(DateTime(True), primary_key=True)
    model_name: Mapped[str] = mapped_column(Text, nullable=False)
    score: Mapped[decimal.Decimal] = mapped_column(Numeric(3, 2), nullable=False)
    publisher_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)

    publisher: Mapped['Publishers'] = relationship('Publishers', back_populates='model_logs')


class RawMetrics(Base):
    __tablename__ = 'raw_metrics'
    __table_args__ = (
        ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ondelete='CASCADE', name='raw_metrics_campaign_id_fkey'),
        ForeignKeyConstraint(['publisher_id'], ['publishers.publisher_id'], ondelete='CASCADE', name='raw_metrics_publisher_id_fkey'),
        PrimaryKeyConstraint('publisher_id', 'bucket_timestamp', 'campaign_id', name='raw_metrics_pkey'),
        Index('raw_metrics_bucket_timestamp_idx', 'bucket_timestamp')
    )

    bucket_timestamp: Mapped[datetime.datetime] = mapped_column(DateTime(True), primary_key=True)
    impression_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text('0'))
    click_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text('0'))
    conversion_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text('0'))
    publisher_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    campaign_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)

    campaign: Mapped['Campaign'] = relationship('Campaign', back_populates='raw_metrics')
    publisher: Mapped['Publishers'] = relationship('Publishers', back_populates='raw_metrics')
