# Auto-generated by sqlacodegen. Do not edit manually.
# Regenerate with: cd db && ./scripts/generate_models.sh

from sqlalchemy import Column, Date, DateTime, Index, Integer, PrimaryKeyConstraint, String, Table, Time
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

class Base(DeclarativeBase):
    pass


t_impression = Table(
    'impression', Base.metadata,
    Column('impression_ts', DateTime(True), nullable=False),
    Column('impression_date', Date, nullable=False),
    Column('impression_time', Time, nullable=False),
    Column('impression_clicks', Integer, nullable=False),
    Index('impression_impression_ts_idx', 'impression_ts')
)


class SchemaMigrations(Base):
    __tablename__ = 'schema_migrations'
    __table_args__ = (
        PrimaryKeyConstraint('version', name='schema_migrations_pkey'),
    )

    version: Mapped[str] = mapped_column(String, primary_key=True)
