stages:
- python-build
- python-test
- test
- secret-detection

include:
- template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: 'true'
  AUTO_DEVOPS_BUILD_IMAGE: 'false'
  AUTO_DEVOPS_TEST: 'false'
  AUTO_DEVOPS_DEPLOY: 'false'

python_build:
  stage: python-build
  image: python:3.11
  script:
    - echo "Upgrading pip + installing dependencies..."
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  only:
    - branches
python_test:
  stage: python-test
  image: python:3.11
  needs:
    - python_build
  script:
    - echo "Running Python tests"
    - pytest #automatically finds test files
  only:
    - branches