include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml

default:
  tags:
    - docker

stages:
  - build
  - test
  - deploy

variables:
  GITHUB_REPO_URL: "https://${GITHUB_TOKEN}@github.com/DuffyEthan/AdGuardSentinel.git"

build:
  stage: build
  image: python:3.11
  script:
    - echo "Upgrading pip + installing dependencies..."
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt --no-cache-dir
  cache:
    paths:
      - .cache/pip
    policy: push
  only:
    - branches

test:
  stage: test
  image: python:3.11
  needs:
    - build
  script:
    - echo "Running Python tests"
    - pip install -r requirements.txt --no-cache-dir
    - pytest || true #automatically finds test files, won't fail if no tests
  cache:
    paths:
      - .cache/pip
  only:
    - branches

mirror_to_github:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - |
      echo "Mirroring ${CI_COMMIT_REF_NAME} branch to GitHub..."


      git config --global user.email "duffyet@tcd.ie"
      git config --global user.name "duffyet"

      git remote add github ${GITHUB_REPO_URL} 2>/dev/null || git remote set-url github ${GITHUB_REPO_URL}

      git push --force github HEAD:${CI_COMMIT_REF_NAME}

      echo "Successfully mirrored to GitHub"

  only:
    - branches
  when: manual #safety