stages:
- python-build
- python-test
- test
- secret-detection

include:
- template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: 'false'
  AUTO_DEVOPS_BUILD_IMAGE: 'false'
  AUTO_DEVOPS_TEST: 'false'
  AUTO_DEVOPS_DEPLOY: 'false'

python_build:
  stage: python-build
  image: python:3.11
  tags:
    - docker
  script:
    - echo "Upgrading pip + installing dependencies..."
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  cache:
    paths:
      - .cache/pip
  only:
    - branches

python_test:
  stage: python-test
  image: python:3.11
  needs:
    - python_build
  tags:
    - docker
  script:
    - echo "Running Python tests"
    - pip install -r requirements.txt
    - pytest || true #automatically finds test files, won't fail if no tests
  cache:
    paths:
      - .cache/pip
  only:
    - branches