services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: app_timescale_db
    restart: unless-stopped
    env_file:
      - ./.secrets/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro

volumes:
  db_data:
