@echo off
setlocal enabledelayedexpansion

set "SCRIPT_DIR=%~dp0"
for %%I in ("%SCRIPT_DIR%..") do set "DB_DIR=%%~fI"
for %%I in ("%SCRIPT_DIR%..\..") do set "PROJECT_ROOT=%%~fI"

:: Load .env from db/ directory
if exist "%DB_DIR%\.env" (
    for /f "usebackq tokens=* delims=" %%A in ("%DB_DIR%\.env") do (
        set "LINE=%%A"
        :: Skip comments and empty lines
        if not "!LINE!"=="" (
            echo !LINE! | findstr /b "#" >nul 2>&1
            if errorlevel 1 (
                set "%%A"
            )
        )
    )
)

:: Validate DATABASE_URL is set
if not defined DATABASE_URL (
    echo ERROR: DATABASE_URL is not set. Create db\.env from db\.env.example
    exit /b 1
)

set "OUTFILE=%PROJECT_ROOT%\app\db\models.py"

:: Convert postgresql:// to postgresql+psycopg:// for SQLAlchemy psycopg v3 driver
set "SQLA_URL=!DATABASE_URL:postgresql://=postgresql+psycopg://!"

echo Generating SQLAlchemy models from: %SQLA_URL%
sqlacodegen "%SQLA_URL%" --outfile "%OUTFILE%"
if errorlevel 1 (
    echo ERROR: sqlacodegen failed.
    exit /b 1
)

:: Prepend header to generated file
set "TMPFILE=%TEMP%\models_tmp_%RANDOM%.py"
(
    echo # Auto-generated by sqlacodegen. Do not edit manually.
    echo # Regenerate with: cd db ^&^& scripts\generate_models.bat
    echo.
    type "%OUTFILE%"
) > "%TMPFILE%"
move /y "%TMPFILE%" "%OUTFILE%" >nul
if errorlevel 1 (
    echo ERROR: Failed to prepend header to models file.
    exit /b 1
)

echo Models written to %OUTFILE%

:: Dump schema.sql from the running TimescaleDB container
set "SCHEMA_FILE=%DB_DIR%\schema.sql"

:: Extract database name from DATABASE_URL robustly via PowerShell URI parsing.
for /f "usebackq delims=" %%D in (`powershell -NoProfile -Command "$u=[System.Uri]::new('%DATABASE_URL%'); $db=$u.AbsolutePath.TrimStart('/'); if([string]::IsNullOrWhiteSpace($db)){ exit 1 }; Write-Output $db"`) do set "DB_NAME=%%D"

if not defined DB_NAME (
    echo ERROR: Could not parse DB name from DATABASE_URL: %DATABASE_URL%
    exit /b 1
)

echo Dumping schema for database "%DB_NAME%" to: %SCHEMA_FILE%
docker compose exec -T db pg_dump --schema-only --no-owner --no-privileges -U postgres "!DB_NAME!" > "%SCHEMA_FILE%"
if errorlevel 1 (
    echo ERROR: Failed to dump schema.
    exit /b 1
)
echo Schema dumped to %SCHEMA_FILE%

endlocal
