#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DB_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Load .env from db/ directory
if [ -f "$DB_DIR/.env" ]; then
    export $(grep -v '^#' "$DB_DIR/.env" | xargs)
fi

DB_URL="${DATABASE_URL:?DATABASE_URL is not set. Create db/.env from db/.env.example}"
OUTFILE="$PROJECT_ROOT/app/db/models.py"

# Convert postgresql:// to postgresql+psycopg:// for SQLAlchemy psycopg v3 driver
SQLA_URL=$(echo "$DB_URL" | sed 's|postgresql://|postgresql+psycopg://|')

echo "Generating SQLAlchemy models from: $SQLA_URL"
sqlacodegen "$SQLA_URL" --outfile "$OUTFILE"

# Prepend header
HEADER="# Auto-generated by sqlacodegen. Do not edit manually.\n# Regenerate with: cd db && ./scripts/generate_models.sh"
TMPFILE=$(mktemp)
printf '%b\n\n' "$HEADER" > "$TMPFILE"
cat "$OUTFILE" >> "$TMPFILE"
mv "$TMPFILE" "$OUTFILE"

echo "Models written to $OUTFILE"

# Dump schema.sql from the running TimescaleDB container
SCHEMA_FILE="$DB_DIR/schema.sql"
DB_NAME=$(echo "$DB_URL" | sed -E 's|.*/([^?]+).*|\1|')
echo "Dumping schema to: $SCHEMA_FILE"
docker compose exec -T db pg_dump \
  --schema-only \
  --no-owner \
  --no-privileges \
  -U postgres \
  "$DB_NAME" > "$SCHEMA_FILE"
echo "Schema dumped to $SCHEMA_FILE"
