-- Seeding is handled by the orchestrator at startup (app/orchestrator.py).
-- Publishers and campaigns are inserted there from the publisher_catalog
-- and campaign_catalog defined in app/ml/publishers/__init__.py.
