# Streamlit reads this via st.secrets["..."]
# If you're running Streamlit locally and DB is in Docker:
DB_HOST = "db"
DB_PORT = "5432"
DB_NAME = "StreamlitDB"
DB_USER = "postgres"
DB_PASSWORD = "changeme"